return {
    {['price'] = 5, ['name'] = 'raw-fish'},
    {['price'] = 10, ['name'] = 'submachine-gun'},
    {['price'] = 20, ['name'] = 'combat-shotgun'},
    {['price'] = 100, ['name'] = 'railgun'},
    {['price'] = 100, ['name'] = 'flamethrower'},
    {['price'] = 200, ['name'] = 'rocket-launcher'},
    {['price'] = 500, ['name'] = 'tank-cannon'},
    {['price'] = 500, ['name'] = 'tank-machine-gun'},
    {['price'] = 1, ['name'] = 'firearm-magazine'},
    {['price'] = 5, ['name'] = 'piercing-rounds-magazine'},
    {['price'] = 20, ['name'] = 'uranium-rounds-magazine'},
    {['price'] = 10, ['name'] = 'shotgun-shell'},
    {['price'] = 10, ['name'] = 'piercing-shotgun-shell'},
    {['price'] = 10, ['name'] = 'railgun-dart'},
    {['price'] = 10, ['name'] = 'flamethrower-ammo'},
    {['price'] = 10, ['name'] = 'rocket'},
    {['price'] = 10, ['name'] = 'explosive-rocket'},
    {['price'] = 10, ['name'] = 'atomic-bomb'},
    {['price'] = 10, ['name'] = 'cannon-shell'},
    {['price'] = 10, ['name'] = 'explosive-cannon-shell'},
    {['price'] = 10, ['name'] = 'explosive-uranium-cannon-shell'},
    {['price'] = 10, ['name'] = 'land-mine'},
    {['price'] = 10, ['name'] = 'grenade'},
    {['price'] = 50, ['name'] = 'cluster-grenade'},
    {['price'] = 10, ['name'] = 'slowdown-capsule'},
    {['price'] = 10, ['name'] = 'poison-capsule'}
}
